apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: theopenfactory
    secureJsonData:
      token: my-super-secret-auth-token-the-open-factory